- name: Basic Troubleshooting BGP
  hosts: Delivery_Network
  gather_facts: false
  collections:
      - servicenow.itsm
      
  vars:
    SN_HOST: "{{ lookup('env', 'SN_HOST') }}"
    SN_USERNAME: "{{ lookup('env', 'SN_USERNAME') }}"
    SN_PASSWORD: "{{ lookup('env', 'SN_PASSWORD') }}"
    switches:
      - ping 10.0.0.1
      - ping 10.0.0.4

  tasks:

    # - name: Backup Network
    #   arista.eos.eos_config:
    #    backup: yes
    #    backup_options:
    #     filename: /tmp/"{{ inventory_hostname }}.cfg"

    - name: Backup arista configuration
      arista.eos.eos_config:
       backup: true
       backup_options:
        dir_path: /tmp/
        filename: "{{ inventory_hostname }}.txt"
      register: config_output

    - name: Grab backups
      ansible.netcommon.net_get:
        src: "{{ config_output }}"
        dest: /tmp/"{{ inventory_hostname }}.cfg"
        protocol: scp
        # username: "{{ ansible_user }}"
        # password: "{{ ansible_password }}"
        # host: "{{ inventory_hostname }}"
      delegate_to: localhost  

    - name: BGP Check
      arista.eos.eos_command:
       commands: show ip bgp summary vrf all
      register: bgp_summary

    - name: Check reachability of switches
      arista.eos.eos_command:
       commands: "{{ switches }}"
      register: result


   # - set_fact:
   #    cacheable: true
   #    bgp_view: "{{ bgp_summary }}"
   #    bgp_ping: "{{ result }}"
   #    status: done
  #     bgp_state: "{{ ansible_eda.event.body.fields.session_state }}"
 #      bgp_prob_neighbor: "{{ ansible_eda.event.body.tags.neighbor_address }}"

    # - name: Network Reachability
    #   debug:
    #     msg: "{{ switches }}"
        
    # - name: BGP Summary details
    #   debug:
    #     msg: "{{ bgp_summary }}"

    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: "{{ SN_USERNAME }}"
        short_description: "XXXXXX"
        description: "Network configurations have been backed up and uploaded"
        attachments:
          - path: "/tmp/{{ inventory_hostname }}_config_backup.txt"
            type: text/plain
            name: "{{ inventory_hostname }}.cfg"
        impact: high
        urgency: high
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
