- name: Basic Troubleshooting BGP
  hosts: Delivery_Network
  gather_facts: true
  collections:
      - servicenow.itsm
      
  vars:
    switches:
      - ping 10.0.0.1
      - ping 10.0.0.4
     SN_HOST: "{{ lookup('env', 'SN_HOST') }}"
     SN_USERNAME: "{{ lookup('env', 'SN_USERNAME') }}"
     SN_PASSWORD: "{{ lookup('env', 'SN_PASSWORD') }}"


  tasks:
  
    - name: BGP Check
      arista.eos.eos_command:
       commands: show ip bgp summary vrf all
      register: bgp_summary

    - name: Check reachability of switches
      arista.eos.eos_command:
       commands: "{{ switches }}"
      register: result

   # - set_fact:
   #    cacheable: true
   #    bgp_view: "{{ bgp_summary }}"
   #    bgp_ping: "{{ result }}"
   #    status: done
  #     bgp_state: "{{ ansible_eda.event.body.fields.session_state }}"
 #      bgp_prob_neighbor: "{{ ansible_eda.event.body.tags.neighbor_address }}"

    - name: Network Reachability
      debug:
        msg: "{{ switches }}"
        
    - name: BGP Summary details
      debug:
        msg: "{{ bgp_summary }}"
        
    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: "{{ SN_USERNAME }}"
        short_description: "User created a new incident using Ansible Automation Platform"
        description: "User {{ SN_USERNAME }} successfully created a new incident!"
        impact: low
        urgency: low
      register: new_incident
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
