- name: Basic Troubleshooting BGP
  hosts: Delivery_Network
  gather_facts: true
  collections:
      - servicenow.itsm
      
  vars:
    SN_HOST: "{{ lookup('env', 'SN_HOST') }}"
    SN_USERNAME: "{{ lookup('env', 'SN_USERNAME') }}"
    SN_PASSWORD: "{{ lookup('env', 'SN_PASSWORD') }}"
    switches:
      - ping 10.0.0.1
      - ping 10.0.0.4

  tasks:

    - name: Backup arista configuration
      arista.eos.eos_config:
       backup: true
       backup_options:
        dir_path: /tmp/
        filename: "{{ inventory_hostname }}.txt"
      register: config_output

    - name: BGP Check
      arista.eos.eos_command:
       commands: show ip bgp summary vrf all
      register: bgp_summary

    - name: Check reachability of switches
      arista.eos.eos_command:
       commands: "{{ switches }}"
      register: result

    - set_fact:
       cacheable: true
       bgp_view: "{{ bgp_summary }}"
       bgp_ping: "{{ result }}"
       bgp_state: "{{ ansible_eda.event.body.fields.session_state }}"
       bgp_prob_neighbor: "{{ ansible_eda.event.body.tags.neighbor_address }}"

    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: "{{ SN_USERNAME }}"
        short_description: "Network Issue detected, Troubleshooting report"
        description: |
          Network Issue:
          Backups: "{{ config_output }}"
          BGP Status: "{{ bgp_summary }}"
          Switch Response: "{{ result }}"
          BGP State: "{{ ansible_eda.event.body.fields.session_state }}"
          BGP Avial. Neighbbors: "{{ ansible_eda.event.body.tags.neighbor_address }}"
        impact: high
        urgency: high
      delegate_to: localhost
      register: new_incident
      run_once: true

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true
      delegate_to: localhost
      run_once: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
      delegate_to: localhost
      run_once: true
