---
- name: Create a directory and setup as samba share
  hosts: node01
  become: true
  collections:
    - redhat.rhel_system_roles
    - redhatinsights.insights
  vars:
   rhsm_username:
   rhsm_password:

  tasks:

    - name: Install subscription manager
      ansible.builtin.package:
        name: subscription-manager
        state: present
    
    - name: Install insights client
      ansible.builtin.package:
        name: insights-client
        state: present
  
    - name: Register RHEL server with subscription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
        
    - name: Register insights client
      ansible.builtin.command: insights-client --register

    - name: Perform initial Insights upload
      ansible.builtin.command: >
        /bin/insights-client
      register: __insights_scan
      changed_when: __insights_scan.rc == 0

