---
- name: Create a directory and setup as samba share
  hosts: node01
  become: true
  collections:
    - redhat.rhel_system_roles
    - redhatinsights.insights
  vars:
   rhsm_username:
   rhsm_password:

  tasks:
  
    - name: Register RHEL server with subscription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ lookup('env', 'REDHAT_USERNAME') }}"
        password: "{{ _password_ }}"
        auto_attach: true
        
    - name: Register insights client
      ansible.builtin.command: insights-client --register
