---
- name: Show configuration of switch
  hosts: ceos02
  connection: local
  gather_facts: false

  vars:
    interface_name: Ethernet1
    interface_description: DISABLED-NA

  tasks:

    - name: Correct Interfaces
      arista.eos.eos_interfaces:
        config:
         - name: Ethernet1
           enabled: false

    - name: Set interface description
      arista.eos.eos_config:
        lines:
          - description "{{ interface_description }}"
        parents: "interface {{ interface_name }}"

    - name: Verify interface configuration
      arista.eos.eos_command:
        commands:
          - show running-config interface {{ interface_name }}
      register: interface_output

    - name: Display interface configuration
      debug:
        var: interface_output.stdout_lines
