---
- 
  name: Create Organizational Units and Group for Ansible Admins
  hosts: windows
  gather_facts: true

  vars:
   org_unit: 
   group_name:
   sandbox:

  tasks:

   - name: Create Organizational Unit
     microsoft.ad.ou:
      name: "{{ org_unit }}"
      state: present
      protect_from_deletion: true

   - name: To view dns_domain from facts
     ansible.builtin.debug:
      msg: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Get DC details
     set_fact:
      domain_name: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Remove trailing dot
     set_fact:
      domain_cleaned: "{{ domain_name | regex_replace('\\.$', '') }}"

   - name: Split domain and reformat as DC=value
     set_fact:
      formatted_domain: "{{ domain_cleaned.split('.') | map('regex_replace', '^', 'DC=') | join(', ') }}"

   - name: Display formatted domain
     debug:
       msg: "{{ formatted_domain }}"

   - name: Create a group in an OU
     microsoft.ad.group:
      identity: "{{ group_name }}"
      scope: global
      path: OU={{ org_unit }},{{ formatted_domain }}
      state: present

  
