---
- 
  name: Create Organizational Units and Group for Ansible Admins
  hosts: windows
  gather_facts: false

  vars:
   org_unit: 
   group_name:
   sandbox:

  tasks:

   - name: Create Organizational Unit
     microsoft.ad.ou:
      name: "{{ org_unit }}"
      state: present
      protect_from_deletion: true

   - name: Transform domain into DC format
     set_fact:
       dc_format: "{{ domain_name.split('.') | map('regex_replace', '^', 'DC=') | join(', ') }}"
    
   - name: Show the DC format
     debug:
       msg: "{{ dc_format }}"

   - name: Create a group in an OU
     microsoft.ad.group:
      identity: "{{ group_name }}"
      scope: global
    #  path: OU="{{ org_unit }}",DC="",DC=svc,DC=cluster,DC=local
    #  state: present

  
