---
- name: Deploy RHEL/Add node
  hosts: localhost
  become: true
  collections:
    - ansible.controller
  vars:

  tasks:
###############INVENTORY###############

   - name: Add Video platform inventory
     ansible.controller.inventory:
       name: "Video Platform Inventory"
       description: "Nodes used for streaming"
       organization: "Default"
       state: present
       controller_host: "https://control"
       controller_username: admin
       controller_password: ansible123!
       validate_certs: false

   - name: Add Streaming Server hosts
     ansible.controller.host:
       name: "{{ item }}"
       description: "Application Nodes"
       inventory: "Video Platform Inventory"
       state: present
       enabled: true
       controller_host: "https://control"
       controller_username: admin
       controller_password: ansible123!
       validate_certs: false
     loop:
       - node01
  
   - name: Add Streaming server group
     ansible.controller.group:
       name: "webservers"
       description: "Application Nodes"
       inventory: "Video Platform Inventory"
       hosts:
         - node01
       variables:
         ansible_user: rhel
       controller_host: "https://control"
       controller_username: admin
       controller_password: ansible123!
       validate_certs: false
