---
- name: Deploy RHEL/Add node
  hosts: localhost
  become: true
  collections:
    - ansible.controller
    
  vars:
    node_name: 

  vars_files:
    controller_details

  tasks:

   - name: Provision System
     ansible.builtin.debug:
       msg: "{{ item }}"
     loop:
       - "CPU usage: 25%"
       - "Warming up the server"
       - "Memory usage: 60%"
       - "Disk space: 80%"
       - "Switching on the network"
       - "Network status: Active"
       - "Ordering Coffee"
       - "Service status: Running"
       - "Making a Meme of Sean Cavanaugh"

   - name: Add Video platform inventory
     ansible.controller.inventory:
       name: "Video Platform Inventory"
       description: "Nodes used for streaming"
       organization: "Default"
       state: present
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false

   - name: Add Streaming Server hosts
     ansible.controller.host:
       name: "{{ item }}"
       description: "Application Nodes"
       inventory: "Video Platform Inventory"
       state: present
       enabled: true
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
     loop:
       - "{{ node_name }}"
  
   - name: Add Streaming server group
     ansible.controller.group:
       name: "webservers"
       description: "Application Nodes"
       inventory: "Video Platform Inventory"
       hosts:
       - "{{ node_name }}"
       variables:
         ansible_user: rhel
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
