---
- 
  name: Configure Windows Server as Domain Controller
  hosts: database_servers
  gather_facts: true

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"
    domain_controller: 
    dns_ip:

  tasks:

   - name: Set a single address on the adapter named Ethernet
     ansible.windows.win_dns_client:
      adapter_names: Ethernet
      dns_servers: "{{ dns_ip }}"

   - name: To view dns_domain from network segment
     ansible.builtin.debug:
      msg: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Ensure local Administrator account has a password
     ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"

   - name: join host to ansible.vagrant with automatic reboot
     microsoft.ad.membership:
      dns_domain_name: "{{ wins_domain }}"
      hostname: dbserver01
      domain_admin_user: Administrator
      domain_admin_password: "{{ safe_password }}"
      domain_server: "{{ domain_controller }}"
     # domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
      state: domain
      reboot: true

   - name: Reboot system after promoting to domain Controller
     ansible.windows.win_reboot:
     when: domain_install.reboot_required
