---
- 
  name: Configure Windows Server as Domain Controller
  hosts: database_servers
  gather_facts: true

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"
    domain_controller: 
    dns_ip:

  tasks:

   - name: Get IP address for a hostname
     ansible.builtin.getent:
      database: hosts
      key: "windows.{{ ansible_interfaces[0].dns_domain }}"
     register: getent_result

   - name: Set a single address on the adapter named Ethernet
     ansible.windows.win_dns_client:
      adapter_names: Ethernet
      dns_servers: "{{ dns_ip }}"

   - name: To view dns_domain from network segment
     ansible.builtin.debug:
      msg: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Ensure local Administrator account has a password
     ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"

   - name: Join host to Domain
     microsoft.ad.membership:
      dns_domain_name: "{{ wins_domain }}"
      hostname: "{{ ansible_host }}"
      domain_admin_user: Administrator
      domain_admin_password: "{{ safe_password }}"
      domain_server: "{{ domain_controller }}"
      state: domain

   # - name: Reboot system after joining domain
   #   ansible.windows.win_reboot:
   #   when: domain_install.reboot_required
