---
- 
  name: Configure Windows Server as Domain Controller
  hosts: domain_controllers
  gather_facts: true

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"

  tasks:

   - name: Set a single address on the adapter named Ethernet
     ansible.windows.win_dns_client:
      adapter_names: Ethernet
      dns_servers: 192.168.34.5

   - name: To view dns_domain from network segment
     ansible.builtin.debug:
      msg: "{{ ansible_interfaces[0].dns_domain }}"

   - name: Ensure local Administrator account has a password
     ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"

   - name: join host to ansible.vagrant with automatic reboot
     microsoft.ad.membership:
      dns_domain_name: 
      hostname: dbserver01
      domain_admin_user: 
      domain_admin_password:
      domain_server: 
     # domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
      state: domain
      reboot: true

   - name: Reboot system after promoting to domain Controller
     ansible.windows.win_reboot:
     when: domain_install.reboot_required
