---
- 
  name: Configure RHEL to join AD
  hosts: webservers
  gather_facts: true

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"
    domain_controller: 
    dns_ip:

  tasks:
  
   - name: Store Domain controller IP
     set_fact:
      ad_hostname: windows.{{ ansible_interfaces[0].dns_domain }}

   - name: Remove trailing dot
     set_fact:
      hostname_cleaned: "{{ ad_hostname | regex_replace('\\.$', '') }}"
  
   - name: Resolve DNS server hostname to IP
     set_fact:
      dns_server_ip: "{{ lookup('dig', ad_hostname) }}"

      #### RHEL Tasks 

   - name: Add DNS from AD to /etc/resolv
     
   
