---
- 
  name: Configure Windows Server as Domain Controller
  hosts: database_servers
  gather_facts: true

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"
    domain_controller: 192.168.1.100
    interface_name: "Ethernet Instance 0"
    static_ip: "192.168.1.101"
    subnet_netmask: 255.255.255.0
  tasks:
   - name: Set static IP address on "{{ interface_name }}"
     ansible.windows.win_shell: netsh interface ipv4 set address name="{{ interface_name }}" static {{ static_ip }} {{ subnet_netmask }} none
   - name: Set a single address on the adapter named Ethernet
     ansible.windows.win_dns_client:
      adapter_names: "{{ interface_name }}"
      dns_servers: "{{ domain_controller }}"

   - name: Ensure local Administrator account has a password
     ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"

   - name: Join host to Domain
     microsoft.ad.membership:
      dns_domain_name: "{{ wins_domain }}"
      hostname: "{{ inventory_hostname }}"
      domain_admin_user: Administrator
      domain_admin_password: "{{ safe_password }}"
      domain_server: "windows"
      state: domain
      reboot: true
