---
- 
  name: Configure Windows Server as Domain Controller
  hosts: database_servers
  gather_facts: true

  vars_files:
    - windows_auth
  vars:
    wins_domain: "{{ ansible_interfaces[0].dns_domain }}"
    domain_controller: 
    dns_ip:

  tasks:
  
   - name: Store Domain controller IP
     set_fact:
      ad_hostname: windows.{{ ansible_interfaces[0].dns_domain }}

   - name: Resolve DNS server hostname to IP
     set_fact:
      dns_server_ip: "{{ lookup('dig', ad_hostname) }}"

   - name: Set a single address on the adapter named Ethernet
     ansible.windows.win_dns_client:
      adapter_names: Ethernet
      dns_servers: "{{ dns_server_ip }}"

   - name: Ensure local Administrator account has a password
     ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ user_password }}"

   - name: Join host to Domain
     microsoft.ad.membership:
      dns_domain_name: "{{ wins_domain }}"
      hostname: "{{ ansible_host }}"
      domain_admin_user: Administrator
      domain_admin_password: "{{ safe_password }}"
      domain_server: "{{ ad_hostname }}"
      state: domain

   # - name: Reboot system after joining domain
   #   ansible.windows.win_reboot:
   #   when: domain_install.reboot_required
