---
- 
  name: Add system to loadbalancer
  hosts: loadbalancer
  gather_facts: true
  become: true

  vars:
    host:

  tasks:
        
   - name: Resolve DNS server hostname to IP
     set_fact:
      host_ip: "{{ lookup('dig', host) }}"

   - name: Add host to loadbalancer Static
     lineinfile:
       path: /etc/haproxy/haproxy.cfg
       regexp: '^## STATIC CONFIG ANSIBLE'
       line: |
            server  static {{ host_ip }}:80 check
       insertafter: '^## STATIC CONFIG ANSIBLE'

   - name: Add host to loadbalancer App
     lineinfile:
       path: /etc/haproxy/haproxy.cfg
       regexp: '^## APP CONFIG ANSIBLE'
       line: |
            server  webapp {{ host_ip }}:80 check
       insertafter: '^## APP CONFIG ANSIBLE'

