---
- name: Configure Network Switch
  hosts: cisco
  gather_facts: no
  
  vars:
   vlan_id: 100
   interface: GigabitEthernet1

  tasks:
  
   - name: Merge provided configuration with device configuration
     cisco.ios.ios_l2_interfaces:
      config:
       - name: GigabitEthernet1
         mode: access
         access:
           vlan: 100
     state: merged      
