---
- name: Configure Network Switch
  hosts: cisco
  gather_facts: no
  
  vars:
    vlan_id: 100
    interface: GigabitEthernet1

  tasks:
    - name: Override device configuration of all L2 interfaces with provided configuration
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ interface }}"
            access:
              vlan: "{{ vlan_id }}"
        state: overridden
