---
- name: Backup and configure Cisco switch
  hosts: cisco
  gather_facts: no
  connection: network_cli
  become: yes
  
  vars:
   vlan_id:
   port: GigabitEthernet1/0/1

  tasks:
  
    - name: Create VLANs 100 to 105
      ios_config:
        lines:
          - vlan {{ vlan_id }}
        save_when: modified

    - name: Configure port for VLAN 100
      cisco.ios.ios_config:
        lines:
          - interface {{ port }}
          - switchport mode access
          - switchport access vlan {{ vlan_id }}
        match: exact
        parents: interface {{ port }}

