---
- name: Configure Network Switch
  hosts: cisco
  gather_facts: no
  
  vars:
   vlan_id:
   port: GigabitEthernet1

  tasks:
  
    - name: Create VLANs
      cisco.ios.ios_config:
        lines:
          - vlan {{ vlan_id }}

    - name: Configure port for VLAN 100
      cisco.ios.ios_config:
        lines:
          - interface {{ port }}
          - switchport mode access
          - switchport access vlan {{ vlan_id }}
        match: exact
        parents: interface {{ port }}

