---
- name: Backup and configure Cisco switch
  hosts: cisco
  gather_facts: no
  connection: network_cli
  become: yes
  
  vars:
   vlan_id:
   acl_port:
   port: GigabitEthernet1/0/1

  tasks:
    - name: Backup Cisco configuration
      cisco.ios.ios_config:
        backup: yes
        dest: "/tmp/cisco_backup_{{ inventory_hostname }}.cfg"

    - name: Configure port for VLAN 100
      cisco.ios.ios_config:
        lines:
          - interface {{ port }}
          - switchport mode access
          - switchport access vlan {{ vlan_id }}
        match: exact
        parents: interface GigabitEthernet1/0/1

    - name: Create ACL for HTTP and HTTPS traffic
      cisco.ios.ios_config:
        lines:
          - ip access-list extended ACL_HTTP
          - permit tcp any any eq {{ ascl_port }}
        match: exact
        parents: ip access-list extended ACL_HTTP

    - name: Apply ACL to the interface
      cisco.ios.ios_config:
        lines:
          - ip access-group ACL_HTTP in
        match: exact
        parents: interface GigabitEthernet1/0/1
