---
- name: Deploy Webapp on RHEL
  hosts: webservers
  gather_facts: true
  become: true
  
  tasks:
  
    - name: Install httpd and Git
      ansible.builtin.package:
        name: 
          - httpd
          - git
        state: present
  
    - name: clone a git repo
      ansible.builtin.git:
        repo: https://github.com/nmartins0611/aap25-roadshow-content.git
        dest: /tmp/repo/
    
    - name: copy all files from one directory to another
      ansible.builtin.copy:
        src: /tmp/repo/aap25-roadshow-content/lab-resources/
        dest: /var/www/html
        remote_src: true
    
  #   - name: Open port 80 for http access
  #     ansible.posix.firewalld:
  #       service: http
  #       permanent: true
  #       state: enabled
  #     notify:
  #       - restart apache

  # handlers:
  #   - name: restart apache
  #     service:
  #       name: httpd
  #       state: restarted
