---
- name: Deploy Webapp on RHEL
  hosts: webservers
  gather_facts: true
  become: true
  
  tasks:
  
    - name: Install httpd and Git
      ansible.builtin.package:
        name: 
          - httpd
          - git
        state: present
  
    - name: clone a git repo
      ansible.builtin.git:
        repo: http://gitea:3000/student/aap25-roadshow-content.git
        dest: /tmp/repo
    
    - name: copy all files from one directory to another
      ansible.builtin.copy:
        src: /tmp/repo/lab-resources/
        dest: /var/www/html
        remote_src: true

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
