---
- name: Deploy Webapp on RHEL
  hosts: webservers
  gather_facts: true
  become: true
  
  tasks:
  
    - name: Install httpd and Git
      ansible.builtin.package:
        name: 
          - httpd
          - git
        state: present
  
    - name: clone a git repo
      ansible.builtin.git:
        repo: https://github.com/nmartins0611/aap25-roadshow-content.git
        dest: /tmp/repo
    
    - name: copy all files from one directory to another
      ansible.builtin.copy:
        src: /tmp/repo/lab-resources/
        dest: /var/www/html
        remote_src: true

    # - name: Tag the page
    #   ansible.builtin.lineinfile:
    #    path: /var/www/html/index.html
    #    line: "This is running on the RHEL Host"
    #    insertafter: "<p>&copy; 2024 TMM - Where comedy lives. All rights reserved.</p>"

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
