---
- name: Gather Node details
  hosts: webservers
  become: yes
  gather_facts: true
  
  tasks:
  
    - name: Collect machine details and format as JSON
      ansible.builtin.set_fact:
        machine_details: >
          {
            "Hostname": "{{ ansible_facts['hostname'] }}",
            "FQDN": "{{ ansible_facts['fqdn'] | default('N/A') }}",
            "OS": "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}",
            "Kernel Version": "{{ ansible_facts['kernel'] }}",
            "Architecture": "{{ ansible_facts['architecture'] }}",
            "CPU Model": "{{ ansible_facts['processor'][0] }}",
            "CPU Cores": "{{ ansible_facts['processor_cores'] | default('N/A') }}",
            "Total Memory (MB)": "{{ ansible_facts['memtotal_mb'] }}",
            "Total Swap (MB)": "{{ ansible_facts['swaptotal_mb'] }}",
            "Default IPv4 Address": "{{ ansible_facts['default_ipv4']['address'] }}",
            "Default IPv4 Interface": "{{ ansible_facts['default_ipv4']['interface'] }}",
            "Disk Information": "{{ ansible_facts['devices'] | join(', ') }}"
          }

    - name: Display machine details in JSON format
      ansible.builtin.debug:
        msg: "{{ machine_details | from_yaml | to_nice_json }}"
