---
- name: Install software using Chocolatey
  hosts: windows

  tasks:

    - name: Run Check Point installer silently
      ansible.windows.win_shell: |
        $installerPath = "C:\ck.exe"
        $silentArgs = "/quiet /norestart /log C:\InstallLogs\CheckpointR81_20.log"
        Start-Process -FilePath $installerPath -ArgumentList $silentArgs -Wait -NoNewWindow
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Installation completed successfully."
        } else {
            Write-Host "Installation failed with exit code: $LASTEXITCODE"
            exit $LASTEXITCODE
        }
      args:
        executable: powershell
