---
- name: Install software using Chocolatey
  hosts: windows
  
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install multiple packages sequentially
      win_chocolatey:
       name: '{{ item }}'
       state: present
      loop:
        - procexp
        - putty
        - windirstat
        - mysql
        - 7zip
        - git
        - notepadplusplus

    - name: Set registry key to disable automatic updates
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
        value: 1
        type: dword
        state: present

    - name: Set Windows Update service to manual
      ansible.windows.win_service:
        name: wuauserv
        start_mode: manual
        state: stopped


