---
- name: Configure IIS ARR on Windows Server
  hosts: database_servers
  tasks:

    - name: Install IIS and required components
      win_feature:
        name:
          - Web-Server
          - Web-Common-Http
          - Web-Dyn-Compression
          - Web-Filtering
          - Web-Stat-Compression
          - Web-Url-Auth
          - Web-WebServer
          - Web-Http-Redirect
        state: present
      become: yes

    # - name: Install Web Platform Installer (WebPI)
    #   win_get_url:
    #     url: "https://download.microsoft.com/download/D/2/A/D2A4F88C-43D1-4BCF-B5EE-3C6F60634A3D/WebPlatformInstaller_amd64_en-US.msi"
    #     dest: C:\WebPI.msi
    #   become: yes

    # - name: Install ARR using WebPI
    #   win_shell: |
    #     msiexec.exe /i C:\WebPI.msi /quiet /norestart
    #     WebPICmd /Install /Products:ARRv3_0 /AcceptEULA
    #   args:
    #     creates: "C:\Program Files\IIS\Application Request Routing"

    # - name: Enable IIS ARR proxy settings
    #   win_shell: |
    #     C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/proxy /enabled:"True" /commit:apphost

    # - name: Add ARR server farm
    #   win_shell: |
    #     C:\Windows\System32\inetsrv\appcmd.exe add config /section:webFarms /+"[name='MyServerFarm']"
    #     C:\Windows\System32\inetsrv\appcmd.exe set config /section:webFarms /[name='MyServerFarm']".applicationRequestRouting.routingRules.useServerName":"false" 

    # - name: Add backend servers to the farm
    #   loop:
    #     - name: "backend1.example.com"
    #       address: "10.0.0.1"
    #     - name: "backend2.example.com"
    #       address: "10.0.0.2"
    #   win_shell: |
    #     C:\Windows\System32\inetsrv\appcmd.exe add config /section:webFarms /[name='MyServerFarm']"/servers/add[serverAddress='{{ item.address }}']"

    # - name: Restart IIS to apply changes
    #   win_service:
    #     name: w3svc
    #     state: restarted
