---
- name: Configure IIS on Windows
  hosts: database_servers
  gather_facts: true
  become: true

  vars:
    iis_sites:
      - name: 'Web Streaming'
        port: '80'
        path: 'C:\sites\webapp'

  tasks:

    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Create site directory structure
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: directory
      with_items: "{{ iis_sites }}"

    - name: Open port for site on the firewall
      community.windows.win_firewall_rule:
        name: "iisport{{ item.port }}"
        enable: true
        state: present
        localport: "{{ item.port }}"
        action: Allow
        direction: In
        protocol: Tcp
      with_items: "{{ iis_sites }}"

      
    - name: Clone Git repository
      win_command:
        cmd: >
          git clone https://github.com/nmartins0611/aap25-roadshow-content.git C:\Temp\repo
      args:
        creates: C:\Temp\repo

    - name: Ensure destination directory exists
      win_file:
        path: "{{ path }}"
        state: directory

    - name: Move contents of cloned repository to destination directory
      win_shell: |
        Get-ChildItem -Path "C:\Temp\aap25-roadshow-content/lab-resources" -Recurse |
        ForEach-Object {
          Move-Item -Path $_.FullName -Destination "C:\sites\webapp" -Force
        }
      args:
        executable: powershell

    - name: Cleanup cloned repository
      win_file:
        path: C:\Temp\repository
        state: absent

