---
- name: Install software using Chocolatey
  hosts: windows
  
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install multiple packages sequentially
      win_chocolatey:
       name: '{{ item }}'
       state: present
      loop:
        - procexp
        - putty
        - windirstat
        - mysql
        - 7zip


