---
- name: Install software using Chocolatey
  hosts: windows

  vars:
    application:
  
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install multiple packages sequentially
      win_chocolatey:
       name: '{{ application }}'
       state: present
