---
- name: Install software using Chocolatey
  hosts: windows
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install ESET antivirus
      win_chocolatey:
        name: eset
        state: present

    - name: Install Malwarebytes
      win_chocolatey:
        name: malwarebytes
        state: present

    - name: Install 7-Zip
      win_chocolatey:
        name: 7zip
        state: present
