---
- name: Execute a VSS PowerShell script on Windows
  hosts: domain_controllers

  tasks:
    - name: Create a shadow copy for the C drive
      win_shell: |
        vssadmin create shadow /for=C:
      register: shadow_create_output

    - name: Display shadow copy creation output
      debug:
        msg: "{{ shadow_create_output.stdout_lines }}"

    - name: Retrieve details of all shadow copies
      win_shell: |
        vssadmin list shadows
      register: shadow_list_output

    - name: Parse and display shadow copy details
      debug:
        msg: >
          {%- for line in shadow_list_output.stdout_lines -%}
          {{ line }}
          {%- endfor -%}
