---
- name: Check and Report Windows Updates
  hosts: domain_controllers
  gather_facts: true

  vars:
    report_path: 'C:\ansible_reports'
    category: Definition Updates

  tasks:
  
    - name: Create site directory structure
      ansible.windows.win_file:
        path: "{{ report_path }}"
        state: directory
        
    - name: Check available updates
      ansible.windows.win_updates:
        category_names: "{{ category }}"
        #log_path: "{{ report_path }}"\Ansible_windows_updates.log
        state: searched
      register: update_result

    - name: Updates found
      debug:
        msg: "{{ update_result }}"

    - name: Generate HTML report
      ansible.windows.win_template:
        src: templates/win_patch_report.html.j2
        dest: C:\inetpub\wwwroot\index.html
      vars:
        updates: "{{ update_result.updates }}"
