---
- name: Check and Report Windows Updates
  hosts: domain_controllers
  tasks:
    - name: Check available updates
      win_updates:
        category_names:
          - Security Updates
        log_path: C:\temp\windows_updates.log
      register: update_result

    - name: Generate HTML report
      template:
        src: templates/win_patch_report.html.j2
        dest: C:\temp\windows_updates_report.html
      vars:
        updates: "{{ update_result.updates }}"
