---
- name: Check and Report Windows Updates
  hosts: domain_controllers
  gather_facts: true

  vars:
    report_path: 'C:\ansible_reports'
    category:
  tasks:
  
    - name: Create site directory structure
      ansible.windows.win_file:
        path: "{{ report_path }}"
        state: directory

    - name: Check if index.html exists and delete it if it does
      ansible.windows.win_file:
        path: C:\inetpub\wwwroot\index.html
        state: absent
      ignore_errors: true
        
    - name: Check available updates
      ansible.windows.win_updates:
        category_names: 
         - "{{ category | default(omit) }}"
#        reboot: "{{ allow_reboot }}"
        state: searched
      register: update_result

    - name: Show us the updates
      debug:
        msg: "{{ category }}"
     
    - name: Generate HTML report
      ansible.windows.win_template:
        src: templates/win_patch_report.html.j2
        dest: C:\inetpub\wwwroot\index.html
      notify: restart_iis
      vars:
        updates: "{{ update_result.updates }}" 
        
  handlers:
    - name: restart_iis
      ansible.windows.win_service:
        name: W3Svc
        state: restarted
        start_mode: auto
