---
- name: Check and Report Windows Updates
  hosts: domain_controllers
  gather_facts: true

  vars:
    report_path: 'C:\ansible_reports'

  tasks:
  
    - name: Create site directory structure
      ansible.windows.win_file:
        path: "{{ report_path }}"
        state: directory
        
    - name: Check available updates
      win_updates:
        category_names:
          - Definition Updates
        #log_path: "{{ report_path }}"\Ansible_windows_updates.log
        state: searched
      register: update_result


    - name: Debug updates result
      debug:
       msg: {{ update_result }}
 

    - name: Generate HTML report
      template:
        src: templates/win_patch_report.html.j2
        dest: C:\inetpub\wwwroot\index.html
      vars:
        updates: "{{ update_result.updates }}"
